export const USER_LOGIN = 'USER_LOGIN';

export const USER_LOGOUT01 = 'USER_LOGOUT01';

export const ACTIVE_SEARCH_BAR = 'ACTIVE_SEARCH_BAR';

export const SAVE_SEARCHED_RECEPIES = 'SAVE_SEARCHED_RECEPIES';

export const LOADING = 'LOADING';

// export const SAVE_RECEPIE_ID = 'SAVE_RECEPIE_ID';

export const SAVE_SEARCHED_INGREDIENTS = 'SAVE_SEARCHED_INGREDIENTS';
